apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-actions-test
  name: github-actions-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-test
  template:
    metadata:
      labels:
        app: github-actions-test
    spec:
      containers:
      - image: milanuzelac/github-actions-test:v1.0.13
        name: github-actions-test